"use client";

import { useStorePrice } from "@/components/store-information-provider";

import { useEffect, useRef } from "react";
import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, ShoppingBag, ShieldCheck, Sparkles, Tag, Trash2, X } from "lucide-react";
import { useCartStore } from "@/store/cart";

import { toast } from "@/components/ui/toaster";
import { validateCoupon } from "@/server/actions/coupons";

export function CartDrawer() {
  const { isOpen, closeCart, items, removeItem, updateQuantity, subtotal, discount, shipping, total, couponCode, applyCoupon, removeCoupon, orderNotes, setOrderNotes } = useCartStore();
  const drawerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") closeCart(); };
    if (isOpen) { document.addEventListener("keydown", closeOnEscape); document.body.style.overflow = "hidden"; }
    return () => { document.removeEventListener("keydown", closeOnEscape); document.body.style.overflow = ""; };
  }, [isOpen, closeCart]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60]">
      <button type="button" aria-label="Close cart" onClick={closeCart} className="absolute inset-0 cursor-default bg-[#163d5c]/40 backdrop-blur-sm" />
      <aside ref={drawerRef} aria-label="Shopping Bag" className="absolute right-0 top-0 flex h-full w-full max-w-[430px] flex-col bg-[#f7fcff] shadow-[-18px_0_52px_rgba(24,89,132,.22)] animate-slideInLeft">
        <header className="relative overflow-hidden bg-[#248fd6] px-5 py-5 text-white"><div className="absolute -right-12 -top-10 h-36 w-36 rounded-full border-[19px] border-white/10" /><div className="relative flex items-center justify-between"><div className="flex items-center gap-3"><span role="img" aria-label="Kids Toy Castle logo" className="h-10 w-10 rounded-xl bg-white bg-cover bg-center shadow-sm" style={{ backgroundImage: "url('/favicon.ico')" }} /><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#ffe783]">Kids Toy Castle</p><h2 className="font-serif text-xl font-bold">Shopping Bag</h2></div></div><button type="button" onClick={closeCart} aria-label="Close bag" className="grid h-10 w-10 place-items-center rounded-xl bg-white/15 transition hover:bg-white/25"><X className="h-5 w-5" /></button></div>{items.length > 0 && <p className="relative mt-4 inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-semibold"><ShoppingBag className="h-3.5 w-3.5" /> {items.reduce((count, item) => count + item.quantity, 0)} items selected</p>}</header>

        {items.length === 0 ? <EmptyBag closeCart={closeCart} /> : <><div className="flex-1 overflow-y-auto p-4 sm:p-5"><div className="space-y-3">{items.map((item) => <CartItem key={item.id} item={item} closeCart={closeCart} removeItem={removeItem} updateQuantity={updateQuantity} />)}</div><CouponBox couponCode={couponCode} applyCoupon={applyCoupon} removeCoupon={removeCoupon} /><textarea value={orderNotes} onChange={(event) => setOrderNotes(event.target.value)} rows={2} placeholder="Order note (optional)" className="mt-3 w-full resize-none rounded-2xl border border-[#dceef8] bg-white px-4 py-3 text-sm text-[#234963] outline-none placeholder:text-[#9db2c1] focus:border-[#248fd6]" /></div><CartSummary subtotal={subtotal} discount={discount} shipping={shipping} total={total} closeCart={closeCart} /></>}
      </aside>
    </div>
  );
}

function EmptyBag({ closeCart }: { closeCart: () => void }) { return <div className="flex flex-1 flex-col items-center justify-center px-8 text-center"><span className="grid h-20 w-20 place-items-center rounded-3xl bg-[#e4f5ff] text-[#248fd6]"><ShoppingBag className="h-9 w-9" /></span><h3 className="mt-5 font-serif text-2xl font-bold text-[#1b588b]">Your bag is empty</h3><p className="mt-2 max-w-xs text-sm leading-6 text-[#6b8497]">Pick a favourite toy and it will appear right here.</p><Link href="/new-arrivals" onClick={closeCart} className="mt-6 rounded-xl bg-[#f06a9f] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#db4e87]">Explore toys</Link></div>; }
function CartItem({ item, closeCart, removeItem, updateQuantity }: { item: ReturnType<typeof useCartStore.getState>["items"][number]; closeCart: () => void; removeItem: (id: string) => void; updateQuantity: (id: string, quantity: number) => void }) {
  const formatPrice = useStorePrice(); return <article className="flex gap-3 rounded-2xl border border-[#dceef8] bg-white p-3 shadow-[0_5px_14px_rgba(43,123,174,.06)]"><div className="relative h-[82px] w-[72px] shrink-0 overflow-hidden rounded-xl bg-[#eaf7ff]">{(item.variant?.image || item.product.images[0]?.url) ? <Image src={item.variant?.image || item.product.images[0].url} alt={item.product.name} fill sizes="72px" className="object-cover" /> : <span className="grid h-full place-items-center text-2xl">🧸</span>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><Link href={`/product/${item.product.slug}`} onClick={closeCart} className="line-clamp-2 text-sm font-bold leading-5 text-[#234963] transition hover:text-[#248fd6]">{item.product.name}</Link><button type="button" aria-label={`Remove ${item.product.name}`} onClick={() => { removeItem(item.id); toast.info("Item removed from bag"); }} className="shrink-0 rounded-lg p-1 text-[#e66b8e] transition hover:bg-[#fff0f4] hover:text-[#c93865]"><Trash2 className="h-4 w-4" /></button></div>{item.variant && <p className="mt-1 text-xs text-[#7895aa]">{[item.variant.name, item.variant.color, item.variant.size].filter(Boolean).join(" / ") || item.variant.sku}</p>}<div className="mt-3 flex items-center justify-between"><div className="flex items-center overflow-hidden rounded-lg border border-[#c9e3f3] bg-[#f5fbff]"><button type="button" aria-label="Decrease quantity" onClick={() => updateQuantity(item.id, item.quantity - 1)} className="grid h-8 w-8 place-items-center text-[#49728f] hover:bg-[#dff3ff]"><Minus className="h-3.5 w-3.5" /></button><span className="grid h-8 w-7 place-items-center text-sm font-bold text-[#234963]">{item.quantity}</span><button type="button" aria-label="Increase quantity" onClick={() => updateQuantity(item.id, item.quantity + 1)} className="grid h-8 w-8 place-items-center text-[#49728f] hover:bg-[#dff3ff]"><Plus className="h-3.5 w-3.5" /></button></div><p className="text-sm font-bold text-[#e8548b]">{formatPrice(item.price * item.quantity)}</p></div></div></article>; }
function CouponBox({ couponCode, applyCoupon, removeCoupon }: { couponCode?: string; applyCoupon: ReturnType<typeof useCartStore.getState>["applyCoupon"]; removeCoupon: () => void }) { return <div className="mt-5 rounded-2xl border border-[#dceef8] bg-white p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-[#234963]"><Tag className="h-4 w-4 text-[#e8a11b]" /> Coupon code</div>{couponCode ? <div className="flex items-center gap-2"><span className="flex-1 rounded-lg bg-[#eaf8ef] px-3 py-2 text-sm font-bold text-[#39784f]">✓ {couponCode} applied</span><button type="button" onClick={removeCoupon} className="text-xs font-bold text-[#dc4e78] hover:underline">Remove</button></div> : <form className="flex gap-2" onSubmit={async (event) => { event.preventDefault(); const input = event.currentTarget.elements.namedItem("coupon") as HTMLInputElement; const code = input.value.trim(); if (!code) return; const response = await validateCoupon(code); if (response.ok) { applyCoupon({ code: code.toUpperCase(), type: response.type ?? "percentage", value: response.value ?? 0, maxDiscount: response.maxDiscount }); toast.success("Coupon applied"); input.value = ""; } else toast.error(response.error ?? "Invalid coupon code"); }}><input name="coupon" type="text" placeholder="Enter code" className="h-10 min-w-0 flex-1 rounded-lg border border-[#c9e3f3] bg-[#f8fcff] px-3 text-sm text-[#234963] outline-none placeholder:text-[#a1b4c2] focus:border-[#248fd6]" /><button type="submit" className="rounded-lg bg-[#e4f5ff] px-3 text-xs font-bold text-[#217ab6] transition hover:bg-[#ccecff]">Apply</button></form>}</div>; }
function CartSummary({ subtotal, discount, shipping, total, closeCart }: { subtotal: number; discount: number; shipping: number; total: number; closeCart: () => void }) {
  const formatPrice = useStorePrice(); return <footer className="border-t border-[#cfe7f5] bg-white p-5 shadow-[0_-8px_20px_rgba(43,123,174,.05)]"><div className="space-y-2 text-sm"><Line label="Subtotal" value={formatPrice(subtotal)} />{discount > 0 && <Line label="Discount" value={`-${formatPrice(discount)}`} green />}<Line label="Delivery" value={shipping === 0 ? "Free" : formatPrice(shipping)} green={shipping === 0} /><div className="mt-3 flex items-center justify-between border-t border-[#e4f0f7] pt-3"><span className="text-base font-bold text-[#234963]">Total</span><span className="text-xl font-bold text-[#e8548b]">{formatPrice(total)}</span></div></div><button type="button" onClick={() => { closeCart(); window.location.href = "/checkout"; }} className="mt-4 flex h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#f06a9f] px-5 text-sm font-bold text-white shadow-[0_8px_18px_rgba(240,106,159,.25)] transition hover:-translate-y-0.5 hover:bg-[#db4e87]"><Sparkles className="h-4 w-4" /> Go to checkout</button><div className="mt-3 flex items-center justify-center gap-1.5 text-[11px] font-medium text-[#5e8a6f]"><ShieldCheck className="h-3.5 w-3.5" /> Secure and simple ordering</div></footer>; }
function Line({ label, value, green }: { label: string; value: string; green?: boolean }) { return <div className="flex justify-between text-[#6b8497]"><span>{label}</span><span className={green ? "font-bold text-[#398352]" : "font-semibold text-[#234963]"}>{value}</span></div>; }
